# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    match(
      type: "development"
    )
    gym(
      scheme: "CICDExample", 
      export_method: "development"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
      type: "appstore"
    )
    gym(
      scheme: "CICDExample"
    )
    # testflight(
    #   skip_submission: true
    # )
  end

  desc "Run tests and generate code coverage"
  lane :test do 
    scan
  end
end
