# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    match(
      type: "development"
    )
    gym(
      scheme: "CICDExample", 
      export_method: "development"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    scan
    match(
      type: "appstore",
      readonly: true
    )

    gym(
      scheme: "CICDExample"
    )
    testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
    slack(
      message: "Upload to testflight!",
      channel: "#cicd_ada_example",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "Run tests and generate code coverage"
  lane :test do 
    scan
    slack(
      message: "Tests succeeded!",
      channel: "#cicd_ada_example",
      slack_url: "https://hooks.slack.com/services/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"
    )

  end
end
